baseURL = 'https://example.org/'
languageCode = 'en-GB'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'About Me'
    pageRef = '/page/aboutme'
    weight = 20


[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
