baseURL = 'http://viki-scull.github.io'
languageCode = 'en-GB'
title = 'Viki Scull Portfolio'
theme = 'my-custom-theme'
[markup.goldmark.renderer] 
	unsafe= true

[caches]
  [caches.images]
    dir = ':cacheDir/images'